### ISSUE TITLE
missing elf file for bootloader

### ISSUE THREAD

**Issue by blacktigersoftware** [sparkfun/PSoC_Arduino_Support#9]
Pull code, open project.  Open Bootloader project.  Double-click 'Bootloadable' instance.  On 'Dependencies tab' specify hex and elf file.  Hex file is provided in git, elf file is not.  Project unable to build with missing elf file.

**Comment by mhord** [comment]
You've got to build the "Bootloader" project first; that will generate the elf file. Make sure you're building on "Release" rather than "Debug".

I just tried it; you'll need to delete the APDS-9960, MicroOLED, and WiFi libraries from the Uno_Blocks project before Uno_Blocks will build. But if you build Bootloader and remove those libraries (from the project explorer; they're not present in the repo), it should build fine.

**Comment by blacktigersoftware** [comment]
Okay, thanks.  I sorta got it working.  Now, I just have to figure out what is the right stuff to delete.  I think I deleted too much.  I just wanted the basic Arduino stuff as a generic project so I can add my own stuff.  Servo's, StripLights, etc..... Don't have 'em, don't need 'em.
